project:
  type: website
  output-dir: docs
  
website:
  cookie-consent:
    type: express
    style: headline
    palette: dark  
  title: "ENVR 282: Research Methods in Environmental Science"
  navbar:
    background: "#881124"
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:Labs
      - sidebar:Lectures
      
  sidebar:
    - id: Labs
      title: "Labs"
      style: "docked"
      background: "#B2B3B2"
      contents: 
       - getting_started.qmd
       - Lab_1.qmd
       - Lab_2.qmd
       - Lab_3.qmd
       - Lab_4.qmd
       - Lab_5.qmd
    - id: Lectures
      title: "Lectures"
      style: "docked"
      background: "#B2B3B2"
      contents: 
       - lec_1.qmd
       - lec_2.qmd
       - lec_3.qmd
       - lec_4.qmd
       - lec_5.qmd
       - lec_6.qmd
       - lec_7.qmd

format:
  html:
    theme: flatly
    mainfont: arial
    css: styles.css
    toc: true

editor: visual


