project:
  type: website
  output-dir: docs
  
website:
  cookie-consent:
    type: express
    style: headline
    palette: dark  
  title: "ENVR 282: Research Methods in Environmental Science"
  navbar:
    background: "#881124"
    search: true
    left:
      - href: index.qmd
        text: Home
      - sidebar:Labs

  sidebar:
    - id: Labs
      title: "Labs"
      style: "docked"
      background: "#B2B3B2"
      contents: 
       - getting_started.qmd
       - Lab_1.qmd
       - Lab_2.qmd

format:
  html:
    theme: flatly
    mainfont: arial
    css: styles.css
    toc: true

editor: visual


